server:
  port: 8080

spring:
  application:
    name: emirates-api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Route to Backend API
        - id: backend-api
          uri: http://localhost:3000
          predicates:
            - Path=/api/apps/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendCircuitBreaker
                fallbackUri: forward:/fallback/backend
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
        
        # Health check route
        - id: health-check
          uri: http://localhost:3000
          predicates:
            - Path=/health/**
          filters:
            - name: CircuitBreaker
              args:
                name: healthCircuitBreaker
                fallbackUri: forward:/fallback/health
    
    # Circuit Breaker Configuration
    circuitbreaker:
      resilience4j:
        instances:
          backendCircuitBreaker:
            sliding-window-size: 10
            minimum-number-of-calls: 5
            failure-rate-threshold: 50
            wait-duration-in-open-state: 30s
          healthCircuitBreaker:
            sliding-window-size: 5
            minimum-number-of-calls: 3
            failure-rate-threshold: 30
            wait-duration-in-open-state: 10s

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.emirates.apigateway: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 